In [3]:
import numpy as np

np.sort
Return a sorted copy of an array.

https://numpy.org/doc/stable/reference/generated/numpy.sort.html

b = np.random.randint(1,100,24).reshape(6,4)
b

In [4]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[61, 81, 61, 58],
       [71, 26, 52, 46],
       [62, 29,  6, 67],
       [18,  7, 72, 73],
       [35, 17, 98, 93],
       [58, 72, 24, 36]])

In [5]:
np.sort(b)

array([[58, 61, 61, 81],
       [26, 46, 52, 71],
       [ 6, 29, 62, 67],
       [ 7, 18, 72, 73],
       [17, 35, 93, 98],
       [24, 36, 58, 72]])

In [6]:
np.sort(b, axis=1)

array([[58, 61, 61, 81],
       [26, 46, 52, 71],
       [ 6, 29, 62, 67],
       [ 7, 18, 72, 73],
       [17, 35, 93, 98],
       [24, 36, 58, 72]])

In [7]:
np.sort(b,axis=0)

array([[18,  7,  6, 36],
       [35, 17, 24, 46],
       [58, 26, 52, 58],
       [61, 29, 61, 67],
       [62, 72, 72, 73],
       [71, 81, 98, 93]])

In [8]:
np.append(b,200)

array([ 61,  81,  61,  58,  71,  26,  52,  46,  62,  29,   6,  67,  18,
         7,  72,  73,  35,  17,  98,  93,  58,  72,  24,  36, 200])

In [11]:
#for reversible sorting we will use
np.sort(b)[::-1]

array([[24, 36, 58, 72],
       [17, 35, 93, 98],
       [ 7, 18, 72, 73],
       [ 6, 29, 62, 67],
       [26, 46, 52, 71],
       [58, 61, 61, 81]])

np.append
The numpy.append() appends values along the mentioned axis at the end of the array

In [12]:
np.append(b,300)

array([ 61,  81,  61,  58,  71,  26,  52,  46,  62,  29,   6,  67,  18,
         7,  72,  73,  35,  17,  98,  93,  58,  72,  24,  36, 300])

In [13]:
b

array([[61, 81, 61, 58],
       [71, 26, 52, 46],
       [62, 29,  6, 67],
       [18,  7, 72, 73],
       [35, 17, 98, 93],
       [58, 72, 24, 36]])

In [14]:
np.append(b,np.random.random((b.shape[0],1)),axis=1)

array([[61.        , 81.        , 61.        , 58.        ,  0.54397235],
       [71.        , 26.        , 52.        , 46.        ,  0.72838424],
       [62.        , 29.        ,  6.        , 67.        ,  0.55977503],
       [18.        ,  7.        , 72.        , 73.        ,  0.48768721],
       [35.        , 17.        , 98.        , 93.        ,  0.13553985],
       [58.        , 72.        , 24.        , 36.        ,  0.95459823]])

In [15]:
# code
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [18]:
np.concatenate((c,d), axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

In [20]:
np.concatenate((c,d),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [25]:
np.unique(d)

array([ 6,  7,  8,  9, 10, 11])

In [26]:
# code
b.shape

(6, 4)

In [27]:
np.expand_dims(b,axis=0).shape

(1, 6, 4)

In [29]:
b

array([[61, 81, 61, 58],
       [71, 26, 52, 46],
       [62, 29,  6, 67],
       [18,  7, 72, 73],
       [35, 17, 98, 93],
       [58, 72, 24, 36]])

In [30]:
np.where(b<30)

(array([1, 2, 2, 3, 3, 4, 5], dtype=int64),
 array([1, 1, 2, 0, 1, 1, 2], dtype=int64))

In [33]:
np.where(b<50,0,b)

array([[61, 81, 61, 58],
       [71,  0, 52,  0],
       [62,  0,  0, 67],
       [ 0,  0, 72, 73],
       [ 0,  0, 98, 93],
       [58, 72,  0,  0]])

In [34]:
np.where(b%2==0,0,b)

array([[61, 81, 61,  0],
       [71,  0,  0,  0],
       [ 0, 29,  0, 67],
       [ 0,  7,  0, 73],
       [35, 17,  0, 93],
       [ 0,  0,  0,  0]])

In [35]:
np.argmax(b)

18

In [36]:
np.argmax(b,axis=1)

array([1, 0, 3, 3, 2, 1], dtype=int64)

In [38]:
np.argmax(b,axis=0)

array([1, 0, 4, 4], dtype=int64)

In [39]:
np.argmin(b)

10

In [40]:
np.argmin(b,axis=1)

array([3, 1, 2, 1, 1, 2], dtype=int64)

In [41]:
np.cumsum(b)

array([  61,  142,  203,  261,  332,  358,  410,  456,  518,  547,  553,
        620,  638,  645,  717,  790,  825,  842,  940, 1033, 1091, 1163,
       1187, 1223])

In [42]:
np.cumsum(b,axis=1)

array([[ 61, 142, 203, 261],
       [ 71,  97, 149, 195],
       [ 62,  91,  97, 164],
       [ 18,  25,  97, 170],
       [ 35,  52, 150, 243],
       [ 58, 130, 154, 190]])

In [43]:
np.cumsum(b,axis=0)

array([[ 61,  81,  61,  58],
       [132, 107, 113, 104],
       [194, 136, 119, 171],
       [212, 143, 191, 244],
       [247, 160, 289, 337],
       [305, 232, 313, 373]])

In [44]:
np.histogram(b,bins=[0,10,20,30,40,50,60])

(array([2, 2, 3, 2, 1, 3], dtype=int64), array([ 0, 10, 20, 30, 40, 50, 60]))

In [45]:
salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])

np.corrcoef(salary,experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

In [46]:
np.corrcoef(salary,experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

In [47]:
b

array([[61, 81, 61, 58],
       [71, 26, 52, 46],
       [62, 29,  6, 67],
       [18,  7, 72, 73],
       [35, 17, 98, 93],
       [58, 72, 24, 36]])

In [50]:
items=[1,3,44,55,4,59,90,40]
b[np.isin(b,items)]

array([], dtype=int32)