In [3]:
import numpy as np

Q-1 Create a null vector of size 10 but the fifth value which is 1.

In [5]:
import numpy as np

In [13]:
a=np.nan*np.empty(10)
a[4]=1
a

array([nan, nan, nan, nan,  1., nan, nan, nan, nan, nan])

Ask user to input two numbers a, b. Write a program to generate a random array of shape (a, b) and print the array and avg of the array


In [23]:
a,b=map(int,input("enter the two numbers:").split())
x=np.random.random((a,b))
print(x)
print(x.mean())

[[0.17936816 0.58020797]
 [0.33719289 0.24066943]]
0.33435961388150914


Write a function to create a 2d array with 1 on the border and 0 inside. Take 2-D array shape as (a,b) as parameter to function.

In [34]:
def borderarray (a,b):

    x=np.ones((a,b))
    x[1:-1,1:-1] =0
    return(x)
borderarray(4,5)

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

Can you create a identity mattrix of shape (3,4). If yes write code for 

In [36]:
#idientity matrix are those which have square size means number of rows and columls are always same
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### `Q-6:` Create a 5x5 matrix with row values ranging from 0 to 4.

In [42]:
z=np.zeros((5,5))
z+=np.arange(5)
z


array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

### `Q-7:`  Consider a random integer (in range 1 to 100) vector with shape `(10,2)` representing coordinates, and coordinates of a point as array is given. Create an array of distance of each point in the random vectros from the given point. Distance array should be interger type.

```
point = np.array([2,3]) 
```


In [45]:
#code here
a = np.random.randint(1, 100, (10, 2))
p = np.array([2,3])
np.sqrt(np.sum((a-p)**2, axis=1)).astype(int)

array([ 74,  60,  48,  94,  69,  81,  78, 120,  96, 104])

In [46]:
a=np.array([1, 2, 3, 4, 5], ndmin=2)
print(a)

[[1 2 3 4 5]]


In [51]:
import numpy as np
dt=np.dtype("i2")
dt

dtype('int16')

In [53]:
import numpy as np
a=np.array([7,10,2,4,13,16])
med=np.percentile(a,50)
print(med)

8.5


In [56]:
x=np.random.randint(0,100, (11,12))
x= np.array([2,3])

array([[87, 69, 31, 82, 42, 65, 34, 89, 18,  3, 87, 72],
       [58, 41,  3, 96, 12, 14,  0, 72, 14,  6, 34, 42],
       [51, 66, 77,  3,  7, 67, 11, 32, 68, 81, 31, 47],
       [32, 20, 70, 35, 26, 41,  8, 34, 10, 14, 82, 27],
       [15, 33, 33,  7, 34, 58, 61, 15, 86, 71, 28, 98],
       [28, 91, 46, 91, 63, 32, 78, 99,  3,  8, 18,  8],
       [40, 14, 28, 27, 46, 47, 51, 20, 21, 41,  8, 75],
       [71, 29, 64, 26,  9, 99, 66, 61, 27, 80, 42, 80],
       [72, 43, 82, 90, 24, 31, 65, 78, 94, 58,  4, 62],
       [82, 85, 33,  5,  7, 92, 46,  2, 14, 96, 94, 61],
       [71, 76, 96, 51, 55, 74, 16, 94, 53, 68, 71, 34]])